available_text_models: ["gpt-3.5-turbo", "gpt-4", "text-davinci-003"]

info:
  gpt-3.5-turbo:
    type: chat_completion
    name: ChatGPT
    description: ChatGPT самая популярная модель. Она <b>быстрая</b> и <b>дёшевая</b>. Идеально подходит для повседневных задач. Если есть задачи, с которыми она не может справиться, попробуйте использовать <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.002
    price_per_1000_output_tokens: 0.002

    scores:
      Интеллект: 3
      Скорость: 5
      Дешевизна: 5

  gpt-4:
    type: chat_completion
    name: GPT-4
    description: GPT-4 <b>умшейшая</b> и самая передовая модель в мире. Но она медленнее и не так экономична, как ChatGPT. Лучший выбор для <b>комплексных</b> и интеллектуальных задач.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Интеллект: 5
      Скорость: 2
      Дешевизна: 2

  text-davinci-003:
    type: completion
    name: GPT-3.5
    description: GPT-3.5 устаревшая модель, в сравнении с GPT-4. На самом деле <b>нет причин использовать эту модель</b>, потому что она дороже и медленнее, чем ChatGPT, но примерно такая же умная.


    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.02

    scores:
      Интеллект: 3
      Скорость: 2
      Дешевизна: 3

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006